# Generated by Django 4.2.2 on 2023-07-31 10:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendingMachineUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'db_table': 'vending_machine_user',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
