# Generated by Django 4.2.3 on 2023-07-31 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0005_vendingmachineuser_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VendingMachineUser',
            new_name='User',
        ),
    ]
